# Generated by Django 5.2.4 on 2025-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographypackage',
            name='delivery_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='photographypackage',
            name='duration_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='photographypackage',
            name='includes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photographypackage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photographypackage',
            name='event_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='photographypackage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
