# Generated by Django 5.2.4 on 2025-08-02 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_photographypackage_delivery_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographypackage',
            name='delivery_days',
        ),
        migrations.RemoveField(
            model_name='photographypackage',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='photographypackage',
            name='delivery_time',
            field=models.IntegerField(default=7, help_text='Delivery time in days'),
        ),
        migrations.AddField(
            model_name='photographypackage',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration in hours'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photographypackage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
