# Generated by Django 5.2.4 on 2025-08-02 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_photographypackage_delivery_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
