# Generated by Django 5.2.4 on 2025-08-05 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_event_type_alter_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 5, 17, 39, 56, 760494, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographypackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 5, 17, 40, 4, 435851, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
